### ISSUE TITLE
Fix design issues of `Working On`

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#54]

**Comment by viditagrawal56** [comment]
Hey @thtauhid I was thinking of adding the data related to the "working on" section in the data/johndoe.json so that the data can be retrieved in api/index.ts

Using this approach we can fetch the data in the working on component and easily map over the data and generate consistent working on data.

However, in the current implementation of the working on section the working card component is repeated again and again causing unnecessary repetition of code.

If you feel my approach is correct, Please assign this issue to me :)

**Comment by thtauhid** [comment]
Hi @viditagrawal56 
We are working on planning a new kind of approach to how the data can be fetched. 
Soon we will be posting the details. 

In short, users will have their data saved on their own GitHub profile. 
We'll be just getting the data from there. 

Feel free to take on any of the issues when posted. 


Thanks for your interest.
